# Site settings
title: The HARP Lab
description: The High-performance Automated Reasoning and Programming (HARP) Lab (UAB, UIC, Syracuse)
baseurl: "" #"http://localhost:4000/" #"http://kmicinski.com" #
url: "" #"http://localhost:4000/"  #"http://kmicinski.com"  ##"http://kmicinski.com" 
permalink: pretty
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
